Traceback (most recent call last):
  File "/home/itsmick_/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/itsmick_/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/itsmick_/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/itsmick_/miniconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/itsmick_/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/itsmick_/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/itsmick_/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

temp_df = df1.join(df2, on='name', how='inner',rsuffix=' - df2')
temp_df = temp_df.join(df3, on='name', how='inner',rsuffix=' - df3')
com_df = temp_df.join(df4, on='name', how='inner', rsuffix=' - df4').reset_index()

# com_df = df1.join(df3, on='name', how='inner').reset_index()

com_df = com_df[com_df['average_playtime'] > 0]
com_df.info()
com_df.duplicated(columns=['name','console']).value_counts()
------------------

----- stdout -----
<class 'pandas.core.frame.DataFrame'>
Index: 1907 entries, 0 to 2288
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   name               1907 non-null   object 
 1   metascore          1907 non-null   int64  
 2   console            1907 non-null   object 
 3   userscore          1907 non-null   object 
 4   date               1907 non-null   object 
 5   rank               1907 non-null   int64  
 6   platform           1907 non-null   object 
 7   year               1888 non-null   float64
 8   genre              1907 non-null   object 
 9   NA_sales           1907 non-null   float64
 10  EU_sales           1907 non-null   float64
 11  JP_sales           1907 non-null   float64
 12  other_sales        1907 non-null   float64
 13  global_sales       1907 non-null   float64
 14  appid              1907 non-null   int64  
 15  release_date       1907 non-null   object 
 16  english            1907 non-null   int64  
 17  developer          1907 non-null   object 
 18  publisher          1907 non-null   object 
 19  platforms          1907 non-null   object 
 20  required_age       1907 non-null   int64  
 21  categories         1907 non-null   object 
 22  genres             1907 non-null   object 
 23  steamspy_tags      1907 non-null   object 
 24  achievements       1907 non-null   int64  
 25  positive_ratings   1907 non-null   int64  
 26  negative_ratings   1907 non-null   int64  
 27  average_playtime   1907 non-null   int64  
 28  median_playtime    1907 non-null   int64  
 29  owners             1907 non-null   object 
 30  price              1907 non-null   float64
 31  Launch Price       1907 non-null   float64
 32  Revenue Estimated  1907 non-null   float64
 33  is_aaa             1907 non-null   int64  
 34  total_reviews      1907 non-null   int64  
 35  review_ratio       1907 non-null   float64
dtypes: float64(10), int64(12), object(14)
memory usage: 551.2+ KB
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 9[0m
[1;32m      7[0m com_df [38;5;241m=[39m com_df[com_df[[38;5;124m'[39m[38;5;124maverage_playtime[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m]
[1;32m      8[0m com_df[38;5;241m.[39minfo()
[0;32m----> 9[0m [43mcom_df[49m[38;5;241;43m.[39;49m[43mduplicated[49m[43m([49m[43mcolumns[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mname[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mconsole[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m[38;5;241m.[39mvalue_counts()

[0;31mTypeError[0m: DataFrame.duplicated() got an unexpected keyword argument 'columns'

